# The name of the workflow.
# This is the name that's displayed for status
# badges (commonly embedded in README.md files).
name: build and test

# Trigger this workflow on a push, or pull request to
# the main branch, when either C# or project files changed
on:
  push:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'

# Create an environment variable named DOTNET_VERSION
# and set it as "6.0.x"
env:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use

# Defines a single job named "build-and-test"
jobs:
  build-and-test:

    # When the workflow runs, this is the name that is logged
    # This job will run three times, once for each "os" defined
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    # Each job run contains these five steps
    steps:

    # 1) Check out the source code so that the workflow can access it.
    - uses: actions/checkout@v3

    # 2) Set up the .NET CLI environment for the workflow to use.
    #    The .NET version is specified by the environment variable.
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # 3) Restore the dependencies and tools of a project or solution.
    # - name: Install dependencies
    #   run: dotnet restore
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    - name: Install dependencies
      run: |
        dotnet add package Newtonsoft.Json --version 13.0.1
        dotnet add package harfbuzzsharp --version 2.8.2.3
        dotnet add package skiasharp --version 2.88.3
        dotnet add package QuestPDF --version 2022.11.0

    # 4) Build a project or solution and all of its dependencies.
    - name: Build
      run: dotnet build --configuration Debug --no-restore

    # 5) Test a project or solution.
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Upload buid Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ResumePDF  # will be zipped automatically
        path: bin/Debug/net6.0/

    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'Resume.zip'
        directory: bin/Debug/net6.0
        # exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: See what's going on
      run: pwd; ls -al; find .


    - name: "Check file existence"
      uses: andstor/file-existence-action@v2
      with:
        files: "ResumePDF.zip, Resume.zip"

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        name: "BuildRelease"
        artifacts: "./bin/Debug/net6.0/Resume.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        body: "Quest PDF"
        draft: true
        prerelease: false
        tag: ${{ github.ref }}
  